- name: Check if Java has already been downloaded and unpacked
  stat:
    path: '{{ java_jdk_dir }}'
  register: dir

- name: Download Java JDK
  get_url:
    url: "{{ java_download_url }}"
    dest: /tmp/{{ java_archive_name }}
  when: not dir.stat.exists
  become: yes
  tags:
    - java_install

- name: Create Java directory
  file:
    name: "{{ java_root_dir }}"
    state: directory
  when: not dir.stat.exists
  become: yes
  tags:
    - java_install

# Untar the downloaded Java archive. The owner and group must be set otherwise the folder
# # structure is created using numerical values for these.
- name: Unpack Java JDK
  unarchive:
    src: /tmp/{{ java_archive_name }}
    dest: "{{ java_root_dir }}"
    owner: cloud_user
    group: cloud_user
    remote_src: yes     
  when: not dir.stat.exists
  become: yes
  tags:
    - java_install

# Use the alternatives command to install the appropriate links to the executables in the PATH.
# Alternatives allows multiple versions of Java to be installed with the correct executable
# on the PATH being used.
- name: Install Java alternatives
  alternatives:
    name: java
    link: /usr/bin/java
    path: '{{ java_jdk_dir }}/bin/java'
  become: yes
  tags:
    - java_install_alternatives

# Cleanup install by deleting downloaded Java archive
- name: Delete Java JDK tar.gz file
  file:
    path: /tmp/{{ java_archive_name }}
    state: absent
  become: yes
  tags:
    - java_cleanup
